services:

  backend:
    build:
      context: ./students-api
    container_name: students-backend
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    networks:
      - app-net
    restart: unless-stopped

  frontend:
    build:
      context: ./students-frontend
    container_name: students-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
